# Generated by Django 3.1.2 on 2020-10-31 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='action',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.action'),
        ),
    ]
